export const quizzArr = [
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
  {
    question: "",
    answer1: "",
    answer2: "",
    answer3: "",
    answer4: "",
    correctAnsewer: "",
  },
];
