export const quizzArr = [
  {
    question: "Where Might You Be Offered Ouzo?",
    answer1: "Russia",
    answer2: "Morocco",
    answer3: "India",
    answer4: "Greece",
    correctAnsewer: "answer4",
  },
  {
    question: "What is the word for a female raccoon?",
    answer1: "A Jill",
    answer2: "A Lioness",
    answer3: "A Sow",
    answer4: "A Hembra",
    correctAnsewer: "answer3",
  },
  {
    question:
      "When did the Maastricht Treaty lay the foundation for the European Union?",
    answer1: "1992",
    answer2: "1960",
    answer3: "1977",
    answer4: "1945",
    correctAnsewer: "answer1",
  },
  {
    question: "A loss of memory is known as what?",
    answer1: "Coma",
    answer2: "Amnesia",
    answer3: "Kleptomania",
    answer4: "Insomnia",
    correctAnsewer: "answer2",
  },
  {
    question: "To What Is The Process Of Vulcanisation Applied?",
    answer1: "Plastic",
    answer2: "Rubber",
    answer3: "Iron",
    answer4: "Wood",
    correctAnsewer: "answer2",
  },
  {
    question:
      "What do the Irish call a spirit whose wailing signals imminent death?",
    answer1: "Gremlin",
    answer2: "Wraith",
    answer3: "Poltergeist",
    answer4: "Banshee",
    correctAnsewer: "answer4",
  },
  {
    question: "Which of these countries borders Nigeria?",
    answer1: "Ghana",
    answer2: "Equatorial Guinea",
    answer3: "Chad",
    answer4: "Togo",
    correctAnsewer: "answer3",
  },
  {
    question:
      "Which actor has featured in films including The Matrix and Speed?",
    answer1: "Christian Bale",
    answer2: "Gérard Depardieu",
    answer3: "Shah Rukh Khan",
    answer4: "Keanu Reeves",
    correctAnsewer: "answer4",
  },
  {
    question: "What Is The Male Part Of A Flower Called?",
    answer1: "Stigma",
    answer2: "Style",
    answer3: "Filament",
    answer4: "Stamen",
    correctAnsewer: "answer4",
  },
  {
    question: "In Edward Lear's poem, which bird sang to the pussycat?",
    answer1: "The Owl",
    answer2: "The Swan",
    answer3: "The Robin",
    answer4: "The Albatross",
    correctAnsewer: "answer1",
  },
];
